import Head from 'next/head';
import '../styles/globals.css';
import { Toaster } from "react-hot-toast";
import Navbar from '@/components/Navbar';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ally</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300&family=Open+Sans&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Toaster
        toastOptions={{
          className: "toaster",
        }}
      />

      <main>
        <Navbar />
        <Component {...pageProps} />
      </main>
    </>
  );

}
