import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ally</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <Link href="/team"><h2 className={inter.className}>
              Our team <span>-&gt;</span>
            </h2></Link>

        <Link href="/workflows/roles">
          <a>
            <h2 className={inter.className}>
              Enter <span>-&gt;</span>
            </h2>
          </a>
        </Link>
      </main>
    </>
  )
}
