import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from 'components/Button'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ally</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300&family=Open+Sans&display=swap" rel="stylesheet"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
          <Image
            className={styles.logo}
            src="/ally_logo.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
          />
          <Link href="workflow">
          <Button text="Try it out!"/>
          </Link>
        </div>
        <div className={styles.splash}>
          <div className={styles.splashContent}>
            <h1>Automated Workflows for Drone Data Management</h1>
            <div>Automated Workflows for Drone Data Management Ally makes drone data management simple, giving you easy access to automated workflows for your drone data. Drag-and-drop tasks into a custom workflow so you can focus on saving lives and leave the rest to us.</div>
          </div>
        
        </div>
      </main>
    </>
  )
}
